"""
Summary Generator - Community Edition

Generates markdown summaries of folder contents.

This is a simplified reference implementation. The full production version includes:
- Deep semantic analysis of project structure
- Technology stack detection with version inference
- Dependency graph visualization
- Risk assessment and technical debt detection
- Architecture pattern recognition
- Team size and complexity estimation

For the full implementation, see Enterprise Edition.
"""

from typing import Dict, Any
import logging
import os
from src.services.generators.base_generator import BaseGenerator

logger = logging.getLogger(__name__)


class SummaryGenerator(BaseGenerator):
    """
    Generates markdown summaries of folder structures.

    Community Edition: Basic file counting and structure
    Enterprise Edition: Deep semantic analysis with AI insights
    """

    async def generate(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate a basic folder summary.

        This is a simplified implementation with basic statistics.
        Production version provides deep semantic insights.

        Args:
            input_data: Must contain 'folder_path'

        Returns:
            Dict with 'status', 'content', and 'message'
        """
        folder_path = input_data.get("folder_path")

        if not folder_path or not self._validate_folder_path(folder_path):
            return {
                "status": "error",
                "message": "Invalid folder path"
            }

        # Basic statistics only (production version does semantic analysis)
        file_count = 0
        dir_count = 0
        extensions = set()

        for root, dirs, files in os.walk(folder_path):
            dir_count += len(dirs)
            file_count += len(files)
            for f in files:
                ext = os.path.splitext(f)[1]
                if ext:
                    extensions.add(ext)

        summary = f"""# Folder Summary (Basic)

**Note:** This is a basic summary. Enterprise Edition provides:
- Semantic project analysis
- Architecture pattern detection
- Technology stack inference
- Risk and complexity assessment

## Statistics

- **Files:** {file_count}
- **Directories:** {dir_count}
- **File Types:** {', '.join(sorted(extensions)[:10])}

## Detected Technologies

{self._detect_basic_tech(extensions)}

---
*Generated by Community Edition. Upgrade to Enterprise for deep insights.*
"""

        return {
            "status": "success",
            "content": summary,
            "message": "Basic summary generated. Enterprise Edition provides semantic analysis.",
            "edition": "community"
        }

    def _detect_basic_tech(self, extensions: set) -> str:
        """Basic technology detection based on file extensions."""
        tech = []
        if ".py" in extensions:
            tech.append("- Python project")
        if ".js" in extensions or ".jsx" in extensions:
            tech.append("- JavaScript/React project")
        if ".ts" in extensions or ".tsx" in extensions:
            tech.append("- TypeScript project")
        if ".java" in extensions:
            tech.append("- Java project")
        if ".go" in extensions:
            tech.append("- Go project")

        return "\n".join(tech) if tech else "- Unknown/Mixed technology stack"
